# Site settings
name: BitWorlds
title: Tobias Johansson
email: tj22fe@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  A website about my adventures in the Worlds of bits.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tj22fe.github.io" # the base hostname & protocol for your site
github_username: tj22fe

# Build settings
markdown: kramdown
